graph TD
    A{Navbar} --> B[DesktopNav]
    B --> B1[DesktopNavItem]
    B1 --> B2[DesktopNavSubmenu]
    B2 --> B3[CustomMenu]
    B3 --> B4[DesktopNavSubitem]
    A --> C[MobileNav]
    C --> C1[MobileMenuButton]
    C --> C2[MobileNavMenu]
    C2 --> C3[MobileNavMenuItem]
    C3 --> C4[MobileNavSubitem]
